name: faceclip
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.1
  - pip=24.0
  - python=3.8.18
  - readline=8.2
  - setuptools=69.1.1
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
    - absl-py==1.4.0
    - annotated-types==0.7.0
    - anyio==4.5.2
    - appdirs==1.4.4
    - audioread==3.0.0
    - backcall==0.2.0
    - blessed==1.20.0
    - blobfile==2.0.2
    - cachetools==5.3.0
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.7
    - clip==1.0
    - configargparse==1.5.3
    - contourpy==1.1.1
    - cycler==0.11.0
    - decorator==4.4.2
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - dtw==1.4.0
    - einops==0.4.1
    - exceptiongroup==1.3.0
    - face-alignment==1.4.1
    - fasttext-wheel==0.9.2
    - ffmpeg==1.4
    - ffmpeg-python==0.2.0
    - filelock==3.12.0
    - fonttools==4.38.0
    - freetype-py==2.4.0
    - fsspec==2023.1.0
    - ftfy==6.1.1
    - future==0.18.3
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-auth==2.18.0
    - google-auth-oauthlib==0.4.6
    - gpustat==1.1
    - grpcio==1.54.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.14.1
    - idna==3.4
    - imageio==2.34.0
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==6.6.0
    - importlib-resources==6.1.2
    - ipython==7.34.0
    - jedi==0.18.2
    - jiter==0.9.1
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy-loader==0.4
    - librosa==0.9.2
    - llvmlite==0.39.1
    - lmdb==1.4.1
    - loguru==0.7.0
    - lxml==4.9.2
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.6
    - moviepy==1.0.3
    - networkx==3.1
    - numba==0.56.4
    - numpy==1.23.0
    - nvidia-ml-py==11.525.112
    - oauthlib==3.2.2
    - openai==1.97.1
    - opencv-python==4.5.5.64
    - openmesh==1.2.1
    - packaging==23.1
    - pandas==1.3.5
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.2.0
    - platformdirs==3.5.1
    - pooch==1.7.0
    - proglog==0.1.12
    - prompt-toolkit==3.0.38
    - protobuf==3.20.3
    - psbody-mesh==0.4
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pyarrow==15.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybind11==2.10.4
    - pycparser==2.21
    - pycryptodomex==3.17
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pyglet==2.0.10
    - pygments==2.15.1
    - pyopengl==3.1.0
    - pyparsing==3.0.9
    - pyrender==0.1.45
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - regex==2023.5.5
    - requests==2.30.0
    - requests-oauthlib==1.3.1
    - resampy==0.4.2
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.0.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==1.38.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soundfile==0.10.3.post1
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.3.0
    - textgrid==1.5
    - threadpoolctl==3.1.0
    - tifffile==2023.7.10
    - tokenizers==0.13.3
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu102
    - torchvision==0.13.1+cu113
    - tqdm==4.64.0
    - traitlets==5.9.0
    - transformers==4.29.1
    - trimesh==4.1.6
    - typing-extensions==4.6.2
    - umap==0.1.1
    - urllib3==1.26.15
    - wandb==0.16.1
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - zipp==3.15.0
prefix: /opt/conda/envs/faceclip
